// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdlecgymohugxkeaxeyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkbGVjZ3ltb2h1Z3hrZWF4ZXlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDkxMTgsImV4cCI6MjA3MjMyNTExOH0.RoRcYTMgU2xAlC_21RQVfx1Un5NBkZk-C7--mQ0r6_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});